### ISSUE TITLE
Daemon List 조회 시 권한 문제

### ISSUE THREAD

**Issue by canopus80** [goody80/Ralf_Dev#8]
kim.so@mesos-slave-02:/data/vault/Source$ zinst start filebeat
/usr/bin/zinst: line 2019: /data/vault/Source/Daemon_ctrl.log: Permission denied
logspout: unrecognized service
filebeat is unrecognized service
kim.so@mesos-slave-02:/data/vault/Source$

**Comment by ralfyang** [comment]
issue clear via https://github.com/goody80/Ralf_Dev/commit/8965755a73a99ad504e58319a65f8f1749e5800d
